servoPin:
  head:
    rotateHead: 12
    neck: 14
    neckLeft: 17
    neckRight: 1
  eye:
    eyeX: 0
    eyeY: 16
  mouth: 
    jaw: 15
  rightHand:
    arm:
      shoulder: 2
      omoplate: 3
      rotateArm: 4
      bicep: 5 
    hand:
      wrist: 6
      thumb: 7
      index: 8
      middle: 9
      ring: 10
      pinky: 11
  leftHand:
    arm:
      shoulder: 18
      omoplate: 19
      rotateArm: 20
      bicep: 21
    hand:
      wrist: 22
      thumb: 23
      index: 24
      middle: 25
      ring: 26
      pinky: 27




initialPosition:
  - 90
  - 30
  - 10
  - 90
  - 0
  - 90
  - 0
  - 0
  - 0
  - 0
  - 0
  - 90
  - 0
  - 90
  - 50
  - 120
  - 90
  - 30
  - 10
  - 90
  - 0
  - 90
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0

currentPosition:
  - 90
  - 30
  - 10
  - 90
  - 0
  - 90
  - 0
  - 0
  - 0
  - 0
  - 0
  - 90
  - 0
  - 90
  - 50
  - 120
  - 90
  - 30
  - 10
  - 90
  - 0
  - 90
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0




minPosition:
  - 60
  - 60
  - 0
  - 10
  - 40
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 30
  - 180
  - 20
  - 50
  - 110
  - 60
  - 0
  - 10
  - 40
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0




maxPosition:
  - 120
  - 110
  - 180
  - 80
  - 180
  - 90
  - 180
  - 180
  - 180
  - 180
  - 180
  - 180
  - 150
  - 180
  - 60
  - 110
  - 160
  - 130
  - 180
  - 80
  - 180
  - 90
  - 180
  - 180
  - 180
  - 180
  - 180
  - 180
  - 180
  - 180
  - 180
  - 180








