servoPin:
  head:
    rotateHead: 11
    neck: 12
    neckLeft: 14
    neckRight: 13
  eye:
    eyeX: 10
    eyeY: 26
  mouth: 
    jaw: 15
  rightHand:
    arm:
      shoulder: 0
      omoplate: 1
      rotateArm: 2
      bicep: 3 
    hand:
      wrist: 4
      thumb: 5
      index: 6
      middle: 7
      ring: 8
      pinky: 9
  leftHand:
    arm:
      shoulder: 16
      omoplate: 17
      rotateArm: 18
      bicep: 19
    hand:
      wrist: 20
      thumb: 21
      index: 22
      middle: 23
      ring: 24
      pinky: 25




initialPosition:
  head:
    rotateHead: 90
    neck: 30
    neckLeft: 85
    neckRight: 100
  eye:
    eyeX: 90
    eyeY: 120
  mouth: 
    jaw: 15
  rightHand:
    arm:
      shoulder: 90
      omoplate: 90
      rotateArm: 90
      bicep: 90
    hand:
      wrist: 90
      thumb: 0
      index: 0
      middle: 0
      ring: 0
      pinky: 0
  leftHand:
    arm:
      shoulder: 90
      omoplate: 100
      rotateArm: 45
      bicep: 90
    hand:
      wrist: 90
      thumb: 0
      index: 0
      middle: 0
      ring: 0
      pinky: 0

currentPosition:
  head:
    rotateHead: 90
    neck: 30
    neckLeft: 85
    neckRight: 100
  eye:
    eyeX: 90
    eyeY: 120
  mouth: 
    jaw: 15
  rightHand:
    arm:
      shoulder: 90
      omoplate: 90
      rotateArm: 90
      bicep: 90
    hand:
      wrist: 90
      thumb: 0
      index: 0
      middle: 0
      ring: 0
      pinky: 0
  leftHand:
    arm:
      shoulder: 90
      omoplate: 100
      rotateArm: 45
      bicep: 90
    hand:
      wrist: 90
      thumb: 0
      index: 0
      middle: 0
      ring: 0
      pinky: 0


